config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :movies do
    resources :bookmarks, only: [:new, :create]
  end

  resources :lists do
    resources :bookmarks
  end

  resources :bookmarks, only: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  before_destroy :check_for_bookmarks

  has_many :bookmarks, dependent: :destroy

  validates :title, :overview, presence: true
  validates :title, uniqueness: { scope: :overview }

  private

  def check_for_bookmarks
    if bookmarks.any?
      raise ActiveRecord::InvalidForeignKey.new('Cannot delete movie with associated bookmarks')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @movie = Movie.find(params[:movie_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params[:movie_id])
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to @movie, notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.'
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new bookmark</h1>

<%= form_with(model: [@list, @bookmark], local: true) do |form| %>
  <%= form.label :comment %>
  <%= form.text_area :comment %>

  <%= form.label :movie_id %>
  <%= form.collection_select :movie_id, Movie.all, :id, :title %>

  <%= form.submit "Add Bookmark" %>
<% end %>

<%= link_to "Back", list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All Lists</h1>

<% @lists.each do |list| %>
  <h2><%= link_to list.name, list_path(list) %></h2>
<% end %>

<%= link_to "New List", new_list_path %>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
h1><%= @list.name %></h1>

<%= link_to 'Back to lists', lists_path %>

<%= button_to 'Delete', list_path(@list), method: :delete, data: { confirm: 'Are you sure you want to delete this list?' } %>

app/views/movies/new.html.erb
<h1>Add a new movie</h1>

<%= form_with(model: @movie, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :overview %>
  <%= form.text_area :overview %>

  <%= form.label :poster_url %>
  <%= form.text_field :poster_url %>

  <%= form.label :rating %>
  <%= form.number_field :rating %>

  <%= form.submit "Add Movie" %>
<% end %>